CREATE TABLE Users (
    UserId VARCHAR(255) PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
	Role VARCHAR(255) NOT NULL DEFAULT 'staff',
	Password VARCHAR(255) NOT NULL,
	CreatedAt datetime NOT NULL DEFAULT GETDATE(),
	IsConfirmed BIT NOT NULL DEFAULT 0
); 