        ###ACTIVITIES


GET http://localhost:8000/api/activity

####
POST http://localhost:8000/api/activity
Content-Type: application/json

{
    "ActivityName": "Adults Activities",
    "Description": "Engage your little ones with fun-filled adventures and creative activities at our dedicated Kids' Club",
    "Category": "adults",
    "ImageUrl": "https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?cs=srgb&dl=pexels-thorsten-technoman-338504.jpg&fm=jpg"
}
