
//health check
GET http://localhost:8000/health

### //get all users
GET http://localhost:8000/api/users

### //create user
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "FirstName": "Isaac",
    "LastName": "Kilimo",
    "Email": "isaackilimok2@gmail.com",
    "Password": "123456@Ik"
}

### Login user
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
    "Email": "isaackilimok2@gmail.com",
    "Password": "123456@Ik"
}


### update user




PUT http://localhost:8000/api/users/update/bc8c9ffc-efd0-47c4-9c7a-0224b4b4ef90
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiIxZDNkODU4My04OGRlLTRhOWYtYjc1MC1lYTY1NDc0YTM4MDkiLCJQYXNzd29yZCI6IiQyYiQwOCR0TXVZMjBZaERvNzN3TmtPT1N1LjllRXZmY2pLNzEzWnlCTDdKYU0wYmZRVkRTZVNxSE1MSyIsIkVtYWlsIjoidGl0dXMzQGdtYWlsLmNvbSIsImlhdCI6MTcwODk3NzY3NCwiZXhwIjoxNzA5MDY0MDc0fQ.pBE7xA_6CPnuTVTXYENwAruzraBeZNB2jyaYMzSmxys

{
    "FirstName": "Favour",
    "LastName": "Oyewumi53",
    "Email": "favourbuyanzi34@gmail.com"
}


### update the user password
PATCH http://localhost:8000/api/users/patch/bc8c9ffc-efd0-47c4-9c7a-0224b4b4ef90
Content-Type: application/json


{
    "Password": "123456@Ia"
}

### getting single user
GET http://localhost:8000/api/users/single/6bdca77d-fa32-42f8-85f9-c1d06d3cafca


### Deleting a single user
DELETE http://localhost:8000/api/users/delete/6bdca77d-fa32-42f8-85f9-c1d06d3cafca
