### GET All Bookings
GET http://localhost:8000/api/bookings


### Create a Booking
POST http://localhost:8000/api/new/booking
Content-Type: application/json

{
    "Email": "polijo5454@irnini.com",
    "FirstName": "Beyonce",
    "LastName": "Knowles",
    "SpecialRequirements": "Put up a huge picture of me on the wall.",
    "StartDate": "3/21/2024",
    "EndDate": "3/23/2024",
    "AdultsNo": 2,
    "KidsNo": 0,
    "MealPlan": "BB",
    "Name": "Deluxe",
    "Size": "Single"
}

### Get Booking Price
GET http://localhost:8000/api/booking/Standard/Single/BB

### Get Booking By ID
GET http://localhost:8000/api/bookings/237c31a-3a00-4445-b764-cc50ecb5c829

### Get booking by email
GET http://localhost:8000/api/polijo5454@irnini.com/bookings

### Get booking by name
GET http://localhost:8000/api/Beyonce/Knowles

### Get booking by roomID
GET http://localhost:8000/api/booking/room/58c47eeb-c132-4fd5-a893-b180b635c524

### Update Booking
PUT http://localhost:8000/api/booking/update/1e143c81-ad84-4669-8034-99dcb6d6fbaf
Content-Type: application/json

{
    "Email": "polijo5454@irnini.com",
    "FirstName": "Beyonce",
    "LastName": "Knowles",
    "SpecialRequirements": "Champagne in plenty, please.",
    "StartDate": "3/21/2024",
    "EndDate": "3/23/2024",
    "AdultsNo": 1,
    "KidsNo": 1,
    "Total": 9000,
    "RoomId": "sample",
    "MealPlan": "BB",
    "Name": "Deluxe",
    "Size": "Single",
    "IsReserved": true,
    "IsPaid": false
}

### Delete Booking
DELETE http://localhost:8000/api/booking/delete/1e143c81-ad84-4669-8034-99dcb6d6fbaf