
### get all gallery pics
GET http://localhost:8000/api/gallery

### create gallery
POST http://localhost:8000/api/gallery
Content-Type: application/json

{
    "Description" : "White black",
        "Category": "Conferences",
        "PictureUrl": "https://cdn.pixabay.com/photo/2017/03/28/12/16/chairs-2181980_960_720.jpg"  
}

###Get Pictures By Category

GET http://localhost:8000/api/gallery/category/accommodation

### Get one gallery
Get http://localhost:8000/api/gallery/onePicture/0d8b5870-298f-4e96-98cf-45112b08e0cf

### Delete gallery

Delete http://localhost:8000/api/gallery/0d8b5870-298f-4e96-98cf-45112b08e0cf

### Update gallery
PUT http://localhost:8000/api/gallery/0d8b5870-298f-4e96-98cf-45112b08e0cf
Content-Type: application/json

{
  "Description" : "Updated White black",
        "Category": "Conferences",
        "PictureUrl": "https://cdn.pixabay.com/photo/2017/03/28/12/16/chairs-2181980_960_720.jpg"  
}


