
### get all gallerys
GET http://localhost:8000/api/gallery

### create gallery
POST http://localhost:8000/api/gallery
Content-Type: application/json

{
    "Description" : "Zip-Lining",
        "Category": "FunActivities",
        "PictureUrl": "https://cdn.pixabay.com/photo/2016/03/21/05/07/zipline-1270003_960_720.jpg"  
}

###Get Pictures By Category

GET http://localhost:8000/api/gallery/category/accommodation

### Get one gallery
Get http://localhost:8000/api/gallery/0d8b5870-298f-4e96-98cf-45112b08e0cf

### Delete gallery

Delete http://localhost:8000/api/gallery/8c23436b-d736-4a98-aa86-71d5dbdafdf7

### Update gallery
PUT http://localhost:8000/api/gallery/f826f419-6637-47ca-b63d-983dd93693d4
Content-Type: application/json

{
   "Description" : "uPDATEDPresidentialSuite",
        "Category": "PresidentialSuite",
        "PictureUrl": "pictureUrl1234"
}