
### Fetching/getting all notifications
GET http://localhost:8000/api/notifications/

### Fetching/getting all booking notifications
GET http://localhost:8000/api/notifications/bookings/8617f5f0-0d88-456c-a881-b020bcb9603f

### Fetching/getting all individual user notifications
patch http://localhost:8000/api/notifications/update/1
Content-Type: application/json

{
     
}
### Fetching/getting all individual user notifications
DELETE http://localhost:8000/api/notifications/delete/1/8617f5f0-0d88-456c-a881-b020bcb9603f
