### Create offer
POST http://localhost:8000/api/offer
Content-Type: application/json

{
    "OfferImageUrl": "https://images.pexels.com/photos/6249454/pexels-photo-6249454.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

### get all offers
GET http://localhost:8000/api/offer


### Get offers by ID
GET http://localhost:8000/api/offer/single/45cf4a93-0fe3-4310-b649-eaf3fce55396

### Update offer
PUT http://localhost:8000/api/offer/update/45cf4a93-0fe3-4310-b649-eaf3fce55396
Content-Type: application/json

{
    "OfferImageUrl": "polijo5454@irnini.com"
}

### Delete offer
DELETE http://localhost:8000/api/offer/delete/45cf4a93-0fe3-4310-b649-eaf3fce55396