### Create offer
POST http://localhost:8000/api/offer
Content-Type: application/json

{
    "OfferImageUrl": "https://images.pexels.com/photos/20150611/pexels-photo-20150611/free-photo-of-in-red.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

### get all offers
GET http://localhost:8000/api/offer


### Get offers by ID
GET http://localhost:8000/api/offer/single/45cf4a93-0fe3-4310-b649-eaf3fce55396

### Update offer
PUT http://localhost:8000/api/offer/update/4cf5f118-a385-4978-9d57-a9ada1ec4b54
Content-Type: application/json

{
    "OfferImageUrl": "polijo5454@irnini.com"
}

### Delete offer
DELETE http://localhost:8000/api/offer/delete/4cf5f118-a385-4978-9d57-a9ada1ec4b54