
###
GET http://localhost:8000/api/otherService


###
POST http://localhost:8000/api/otherService
Content-Type: application/json


{
    "OtherServiceName": "Kids' Fun Park",
    "Description": "The epitome of fun for the little ones.",
    "ImageUrl": "https://images.pexels.com/photos/12576346/pexels-photo-12576346.jpeg?auto=compress&cs=tinysrgb&w=400"

}


###
PUT http://localhost:8000/api/otherService/de75aa0d-f5a7-494e-931e-27c6099ddb72
Content-Type: application/json

{ 
    "OtherServiceName": "Coffee",
    "Description": "Savor fresh roasts from our barista",
    "ImageUrl": "https://as2.ftcdn.net/v2/jpg/01/05/90/77/1000_F_105907729_4RzHYsHJ2UFt5koUI19fc6VzyFPEjeXe.jpg"
}

###
DELETE http://localhost:8000/api/otherService/def84963-d2a1-402e-8a7a-269535ec35e5
