
###
GET http://localhost:8000/api/otherService


###
POST http://localhost:8000/api/otherService
Content-Type: application/json


{
    "OtherServiceName": "Presidential Suite",
    "Description": "Discover the opulence of royal living",
    "ImageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmmA3W_0DH_A8IiQk5pzMFVzZ6ljhFErKcRf6rhlii8A&s"
}


###
PUT http://localhost:8000/api/otherService/de75aa0d-f5a7-494e-931e-27c6099ddb72
Content-Type: application/json

{ 
    "OtherServiceName": "Coffee",
    "Description": "Savor fresh roasts from our barista",
    "ImageUrl": "https://as2.ftcdn.net/v2/jpg/01/05/90/77/1000_F_105907729_4RzHYsHJ2UFt5koUI19fc6VzyFPEjeXe.jpg"
}

###
DELETE http://localhost:8000/api/otherService/def84963-d2a1-402e-8a7a-269535ec35e5
