
//health check
GET http://localhost:8000/health


### Find category
POST http://localhost:8000/api/category
Content-Type: application/json

{
    "Name": "Deluxe",
    "Size": "Double",
    "MealPlan": "BB"
}

### //get all rooms categories
GET http://localhost:8000/api/category/rooms/category


### Create category
POST http://localhost:8000/api/category/rooms/category
Content-Type: application/json

{
    "Name": "Presidential",
    "Size": "F/Room",
    "MealPlan": "FB",
    "Price": 100000
}

### //get all rooms categories
GET http://localhost:8000/api/category/rooms/category/c48185a8-5762-4076-a1dd-85b0a12979e8


### Create category room
POST http://localhost:8000/api/category/rooms/category
Content-Type: application/json

{
    "Name": "Deluxe",
    "Size": "Double",
    "MealPlan": "BH",
    "Price": 80000

}

### //get single rooms categories
GET http://localhost:8000/api/category/rooms/category/26a6bcca-7e0f-4490-9431-1e6371e71128


### soft delete category
PATCH http://localhost:8000/api/category/rooms/category/softdelete/26a6bcca-7e0f-4490-9431-1e6371e71128
Content-Type: application/json

{
   
}


### update category
PUT http://localhost:8000/api/category/rooms/category/update/26a6bcca-7e0f-4490-9431-1e6371e71128
Content-Type: application/json

{
    "Name": "Deuxel",
    "Size": "2",
    "MealPlan": "HB",
    "Price": 10000
}


### Delete category
DELETE http://localhost:8000/api/category/rooms/category/26a6bcca-7e0f-4490-9431-1e6371e71128



### getting the price of a room
POST http://localhost:8000/api/category/rooms/category/price
Content-Type: application/json

{
    "Name": "Presidential",
    "Size": "F/Room",
    "MealPlan": "FB"
}
