
//health check
GET http://localhost:8000/health



### //get all rooms categories
GET http://localhost:3000/api/category/rooms/category


### //get all rooms categories
GET http://localhost:8000/api/category/rooms/category

### Create category
POST http://localhost:3000/api/category/rooms/category
Content-Type: application/json

{
    "Name": "Superior",
    "Size": "Single",
    "MealPlan": "FB",
    "Price": 12000
}

### //get all rooms categories
GET http://localhost:3000/api/category/rooms/category/c48185a8-5762-4076-a1dd-85b0a12979e8


### Create category room

POST http://localhost:8000/api/category/rooms/category
Content-Type: application/json

{
    "Name": "standard",
    "Size": "Double",
    "MealPlan": "BB",
    "Price": 7000

}

### //get single rooms categories
GET http://localhost:8000/api/category/rooms/category/c48185a8-5762-4076-a1dd-85b0a12979e8


### soft delete category
PATCH http://localhost:8000/api/category/rooms/category/softdelete/15b15ff5-1994-407b-a6fe-97e3525ba56f
Content-Type: application/json

{
   
}


### update category
PUT http://localhost:3000/api/category/rooms/category/update/22c62669-fb1d-4520-b257-6e77116c4daf
Content-Type: application/json

{
    "Name": "Standard",
    "Size": "Single",
    "MealPlan": "HB",
    "Price": 7500
}


### Delete category
DELETE http://localhost:8000/api/category/rooms/category/c48185a8-5762-4076-a1dd-85b0a12979e8

