
//health check
GET http://localhost:3000/health

### //get all rooms
GET http://localhost:3000/api/rooms

### //create room
POST http://localhost:3000/api/rooms
Content-Type: application/json

{
    "RoomPhotoUrl": "Deluxe",
    "RoomNumber": 20,
    "Description": "A beautiful, spacious room well suited for love birds",
    "RoomCategoryId": "a515d485-f643-4469-8b85-db7af1845a1c",
    "Occupants": 4
}

### //get single rooms
GET http://localhost:8000/api/rooms/bda1453a-d5c2-4409-8a4b-0e9c77843317

### //get single rooms

PUT http://localhost:8000/api/rooms/update/bda1453a-d5c2-4409-8a4b-0e9c77843317/15b15ff5-1994-407b-a6fe-97e3525ba56f

Content-Type: application/json

{
    "RoomPhotoUrl": "Deluxe 23",
    "description": "A ggod and spacous room for love birds",
    "Occupants": "Single room nice one",
    "RoomNumber": 25
}

### soft delete category
PATCH http://localhost:8000/api/category/rooms/category/softdelete/c48185a8-5762-4076-a1dd-85b0a12979e8
Content-Type: application/json

{
   
}


### Delete room
DELETE http://localhost:8000/api/rooms/delete/bda1453a-d5c2-4409-8a4b-0e9c77843317