
        ##SERVIVES
###
GET http://localhost:8000/api/service

###
GET http://localhost:8000/api/service/49073f97-3e58-48ae-b4d5-a07b6b00c6c1

###
POST http://localhost:8000/api/service
Content-Type: application/json

{
    "ServiceName": "Adults Activities",
    "Description": "Engage your little ones with fun-filled adventures and creative activities at our dedicated Kids' Club",
    "ImageUrl": "https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?cs=srgb&dl=pexels-thorsten-technoman-338504.jpg&fm=jpg"
}

###
PUT http://localhost:8000/api/service/49073f97-3e58-48ae-b4d5-a07b6b00c6c1
Content-Type: application/json

{
    "ServiceName": "Adults Activities Updated",
    "Description": "Engage your little ones with fun-filled adventures and creative activities at our dedicated Kids' Club",
    "ImageUrl": "https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?cs=srgb&dl=pexels-thorsten-technoman-338504.jpg&fm=jpg"
}


###
DELETE http://localhost:8000/api/service/df9e6afd-97c8-46d9-a49e-e77f1431ce64




