
### get all Event
GET http://localhost:8000/api/events

### get all Event
GET http://localhost:8000/api/events/upcoming/date

### create Event
POST http://localhost:8000/api/events
Content-Type: application/json

{
    "Name": "Another",
    "Description": "An upcoming event for Shusha nyavu at garden city",
    "PosterUrl": "https://images.pexels.com/photos/2608516/pexels-photo-2608516.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "Date": "2023-05-22"
}

### Get one Event
Get http://localhost:8000/api/events/single/255e16f4-f2a7-4255-9e51-98308826754e

### Delete Event

Delete http://localhost:8000/api/events/delete/255e16f4-f2a7-4255-9e51-98308826754e

### Update Event

PUT http://localhost:8000/api/events/update/255e16f4-f2a7-4255-9e51-98308826754e
Content-Type: application/json

{
    "Name": "ShushaNyavu Night",
    "Description": "Party at Garden city Mal",
    "PosterUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7iqi31sz9mNDc-LJ-kdy86XwaXAO9F-fam86TBbs8lg&s",
    "Date": "31012023"
}

